### ISSUE TITLE
Week 12: Combining Tuning Option and Starting Lessons

### ISSUE THREAD

**Issue by SHuntzberry** [gw-sd-2016/ArtificialInstructor#2]
@cctoombs 
@twood02

This week I have completed the tuner, it is not pretty or very detailed but the functionality works perfectly. I have compared it to another tuning software as well as a tuning device and the note results are the same. The pitch detection also works perfectly with each fret, on each string. I have added some code to try and better isolate each note strummed so that each time a note is struck the program only outputs one value. Also, I have started to work out a timing algorithm to match the note struck with a time interval. 

I have started to customize a simple lesson by programming note value, timing, and length. This has not proved as easily as I expected however, I believe that by my next git commit next Sunday, hopefully sooner, I will be able to have a lesson programed and able to be compared to the input from the user. Additionally, I have started to disperse the elements of the project into different classes in order to make my main program less compact so that the code is easier to cycle through.

**Comment by twood02** [comment]
sounds good.  The choice of interface may affect how you want to deal with timing.  One option is to ignore timing and just show a series of notes and expect the user to hit all of them in the right order, meaning that if they hit a note wrong or they have a long pause between notes the system will wait until they correctly hit the note.  The other is more "guitar hero" style where the notes fly by and the user only gets credit if they hit it at the right time.  It sounds like you are aiming for the latter, but you may want to consider if the first option would be a useful starting point that might be simpler to get up and running.
