### ISSUE TITLE
Week 16: Managed to break my github

### ISSUE THREAD

**Issue by SHuntzberry** [gw-sd-2016/ArtificialInstructor#5]
I was working on adding the lesson functionality when I decided to update my latest code to github. Somehow my commit broke my eclipse project because none of my imports are working and my classes seem to be unable to be called, or recognized. Hopefully I will have this issue solved shortly. 

Aside from that I am beginning to be able to get the hard coded lesson note to appear depending on a time stamp. Once I am able to get this, I will be able to adjust the users score depending on when they strum a value. After this is complete I will be able to get full feedback to the user based on their input. Moving on I will be able to use that input to calculate appropriate feedback for the user.

**Comment by twood02** [comment]
oops!
